### PR TITLE
Modified the workout

### PR DESCRIPTION
**Pull request by JustinJiao**
Modified the functionality of the workout page and added an exercise library for storing exercises Then finished setting up some backends.

### CODE REVIEW

**Comment by tjfrench24** [comment]
The code seems to change a lot of the backend and comment out a lot of what was there. If it is still not storing the data that the user inputs in the backend then maybe we should keep more of the backend code that was there. Also I'm not sure what is meant by "muscleRate", so I'm not sure if a user would know either.

**Comment by tjfrench24** [comment]
Changing things such as the import statements is fine if those fix the problem, and there are definitely some great parts of the code, but I'm not sure why part of the code such as the methods to delete a workout by its ID are being commented out.

**Comment by JustinJiao** [comment]
> The code seems to change a lot of the backend and comment out a lot of what was there. If it is still not storing the data that the user inputs in the backend then maybe we should keep more of the backend code that was there. Also I'm not sure what is meant by "muscleRate", so I'm not sure if a user would know either.

Thank you for your reply. Since I wasn't quite sure how I should implement the backend properly, but I didn't want to change the code you originally wrote, I chose to comment them out. Feel free to change my code as they do have a lot of problems. As for the muscle rates it was because I saw in the progress graph that they needed to be tracked, so, I added them here to make it easier for the progress graph to track to get the curve.

**Comment by JustinJiao** [comment]
> Changing things such as the import statements is fine if those fix the problem, and there are definitely some great parts of the code, but I'm not sure why part of the code such as the methods to delete a workout by its ID are being commented out.

Thanks for the reply, sorry that was my question. Since I've been debugging to find the problem, I commented out a part of the code because I wanted to troubleshoot that part first for any problems that might occur. The reason why I commented out the code is because I didn't want to change the code you originally wrote, so I chose to comment them out. You can change my code as much as you want, because indeed there are a lot of problems in the backend files.

**Pull request merged**
